pipeline {
  agent any

  parameters {
    string(name: 'BRANCH', defaultValue: 'main', description: 'Branch to build (used for non-multibranch jobs)')
  }

  tools {
    jdk 'jdk17'           // configure JDK 17 in Jenkins global tools with this name
    maven 'Maven3'        // configure Maven in Jenkins global tools with this name
  }

  environment {
    MVN_CMD = isUnix() ? 'mvn' : 'mvn' // tool wrapper provided by Jenkins tools
    CUCUMBER_REPORT_DIR = 'target/cucumber-reports'
  }

  stages {
    stage('Checkout') {
      steps {
        script {
          if (env.BRANCH_NAME) {
            // Multibranch pipeline: Jenkins already checked out correct branch via 'checkout scm'
            checkout scm
          } else {
            // Single pipeline job: check out the requested branch
            git branch: params.BRANCH, url: env.GIT_URL ?: 'https://github.com/dheerajdevendrajain/AutomationExercise.git', credentialsId: 'git-credentials-id'
          }
        }
      }
    }

    stage('Build') {
      steps {
        script {
          if (isUnix()) {
            sh "${MVN_CMD} --batch-mode clean package -DskipTests=false"
          } else {
            bat "\"%MAVEN_HOME%\\bin\\mvn\" --batch-mode clean package -DskipTests=false"
          }
        }
      }
    }

    stage('Test') {
      steps {
        script {
          if (isUnix()) {
            sh "${MVN_CMD} --batch-mode test"
          } else {
            bat "\"%MAVEN_HOME%\\bin\\mvn\" --batch-mode test"
          }
        }
      }
      post {
        always {
          // ensure reports are generated by maven-cucumber-reporting plugin (configured in pom)
          echo 'Tests finished - collecting reports'
        }
      }
    }

    stage('Publish Reports & Artifacts') {
      steps {
        script {
          // Archive build artifacts (jar/war)
          archiveArtifacts artifacts: 'target/*.jar, target/*.war', allowEmptyArchive: true

          // Publish Surefire/JUnit XML results
          junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml, **/target/failsafe-reports/*.xml'

          // Publish cucumber HTML report if plugin produced it
          publishHTML([
            reportDir: "${CUCUMBER_REPORT_DIR}",
            reportFiles: 'overview-features.html',
            reportName: 'Cucumber Reports',
            allowMissing: true
          ])
        }
      }
    }
  }

  post {
    success {
      echo 'Build succeeded'
    }
    unstable {
      echo 'Build unstable (some tests failed)'
    }
    failure {
      echo 'Build failed'
    }
    always {
      cleanWs()
    }
  }
}
